name: keranjangin
description: "Aplikasi e-commerce untuk belanja kebutuhan harian."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # NETWORK
  http: ^1.2.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  cached_network_image: ^3.3.1
  animations: ^2.1.0
  flutter_credit_card: ^3.0.6

  # FORM & VALIDATION
  form_field_validator: ^1.1.0
  intl: ^0.18.1

  # STATE MANAGEMENT
  provider: ^6.1.5+1

  # AUTH & FIREBASE
  google_sign_in: ^6.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2

  # UTIL
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.3+1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo_splash.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/