// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Kkl50Tz4bWBiygq-vdmT-UDVCj4_qqY',
    appId: '1:384008419137:web:bd559133f722ee0ecc53c0',
    messagingSenderId: '384008419137',
    projectId: 'keranjangin-51f59',
    authDomain: 'keranjangin-51f59.firebaseapp.com',
    storageBucket: 'keranjangin-51f59.firebasestorage.app',
    measurementId: 'G-Y45CMZTY0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATaUO-dZAiMK3lnhmQtlmKp99aefDXkl0',
    appId: '1:384008419137:android:6eacd563e66175a8cc53c0',
    messagingSenderId: '384008419137',
    projectId: 'keranjangin-51f59',
    storageBucket: 'keranjangin-51f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAYdyJ9ILT155xBVn2d3bFJ_OwUHzLKE',
    appId: '1:384008419137:ios:c664c3fa4a2bab65cc53c0',
    messagingSenderId: '384008419137',
    projectId: 'keranjangin-51f59',
    storageBucket: 'keranjangin-51f59.firebasestorage.app',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAYdyJ9ILT155xBVn2d3bFJ_OwUHzLKE',
    appId: '1:384008419137:ios:25870800c13b3996cc53c0',
    messagingSenderId: '384008419137',
    projectId: 'keranjangin-51f59',
    storageBucket: 'keranjangin-51f59.firebasestorage.app',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Kkl50Tz4bWBiygq-vdmT-UDVCj4_qqY',
    appId: '1:384008419137:web:fb3b7c4c7fa4306ccc53c0',
    messagingSenderId: '384008419137',
    projectId: 'keranjangin-51f59',
    authDomain: 'keranjangin-51f59.firebaseapp.com',
    storageBucket: 'keranjangin-51f59.firebasestorage.app',
    measurementId: 'G-H4JZMQCW2G',
  );
}
