import '../models/dummy_bundle_model.dart';
import '../models/dummy_product_model.dart';

class Dummy {
  /// =========================
  /// 🌟 PRODUCTS DATA LENGKAP
  /// =========================
  static List<ProductModel> products = [

    /// 🌱 VEGETABLES
    ProductModel(
      name: 'Carrot',
      weight: '1 kg',
      cover: 'https://i.imgur.com/tGChxbZ.png',
      images: ['https://i.imgur.com/tGChxbZ.png'],
      price: 5,
      mainPrice: 7,
      rating: 4,
      category: 'Vegetables',
    ),
    ProductModel(
      name: 'Broccoli',
      weight: '1 kg',
      cover: 'https://i.imgur.com/tGChxbZ.png',
      images: ['https://i.imgur.com/tGChxbZ.png'],
      price: 6,
      mainPrice: 8,
      rating: 5,
      category: 'Vegetables',
    ),
    ProductModel(
      name: 'Corn',
      weight: '2 pcs',
      cover: 'https://i.imgur.com/6QJ7X8p.png',
      images: ['https://i.imgur.com/6QJ7X8p.png'],
      price: 4,
      mainPrice: 6,
      rating: 4,
      category: 'Vegetables',
    ),
    ProductModel(
      name: 'Chili',
      weight: '500 g',
      cover: 'https://i.imgur.com/3qJ9x9A.png',
      images: ['https://i.imgur.com/3qJ9x9A.png'],
      price: 3,
      mainPrice: 5,
      rating: 5,
      category: 'Vegetables',
    ),
    ProductModel(
      name: 'Tomato',
      weight: '1 kg',
      cover: 'https://i.imgur.com/8yQwT2m.png',
      images: ['https://i.imgur.com/8yQwT2m.png'],
      price: 4,
      mainPrice: 6,
      rating: 4,
      category: 'Vegetables',
    ),

    /// 🥩 MEAT & FISH
    ProductModel(
      name: 'Beef',
      weight: '1 kg',
      cover: 'https://i.imgur.com/5wghZji.png',
      images: ['https://i.imgur.com/5wghZji.png'],
      price: 15,
      mainPrice: 18,
      rating: 4,
      category: 'Meat And Fish',
    ),
    ProductModel(
      name: 'Chicken',
      weight: '1 kg',
      cover: 'https://i.imgur.com/5wghZji.png',
      images: ['https://i.imgur.com/5wghZji.png'],
      price: 12,
      mainPrice: 15,
      rating: 4,
      category: 'Meat And Fish',
    ),
    ProductModel(
      name: 'Salmon',
      weight: '1 kg',
      cover: 'https://i.imgur.com/9yGkL3m.png',
      images: ['https://i.imgur.com/9yGkL3m.png'],
      price: 18,
      mainPrice: 22,
      rating: 5,
      category: 'Meat And Fish',
    ),
    ProductModel(
      name: 'Tuna',
      weight: '1 kg',
      cover: 'https://i.imgur.com/9yGkL3m.png',
      images: ['https://i.imgur.com/9yGkL3m.png'],
      price: 14,
      mainPrice: 17,
      rating: 4,
      category: 'Meat And Fish',
    ),
    ProductModel(
      name: 'Shrimp',
      weight: '500 g',
      cover: 'https://i.imgur.com/4xT8yLp.png',
      images: ['https://i.imgur.com/4xT8yLp.png'],
      price: 10,
      mainPrice: 13,
      rating: 5,
      category: 'Meat And Fish',
    ),

    /// 💊 MEDICINE
    ProductModel(
      name: 'Paracetamol',
      weight: '10 tablets',
      cover: 'https://i.imgur.com/GPsRaFC.png',
      images: ['https://i.imgur.com/GPsRaFC.png'],
      price: 2,
      mainPrice: 3,
      rating: 4,
      category: 'Medicine',
    ),
    ProductModel(
      name: 'Cough Syrup',
      weight: '100 ml',
      cover: 'https://i.imgur.com/2pX9aKj.png',
      images: ['https://i.imgur.com/2pX9aKj.png'],
      price: 4,
      mainPrice: 6,
      rating: 4,
      category: 'Medicine',
    ),
    ProductModel(
      name: 'Vitamins',
      weight: '30 tablets',
      cover: 'https://i.imgur.com/2pX9aKj.png',
      images: ['https://i.imgur.com/2pX9aKj.png'],
      price: 6,
      mainPrice: 8,
      rating: 5,
      category: 'Medicine',
    ),
    ProductModel(
      name: 'Antibiotics',
      weight: '10 capsules',
      cover: 'https://i.imgur.com/2pX9aKj.png',
      images: ['https://i.imgur.com/2pX9aKj.png'],
      price: 7,
      mainPrice: 9,
      rating: 4,
      category: 'Medicine',
    ),

    /// 👶 BABY CARE
    ProductModel(
      name: 'Baby Diapers',
      weight: '20 pcs',
      cover: 'https://i.imgur.com/mGRqfnc.png',
      images: ['https://i.imgur.com/mGRqfnc.png'],
      price: 12,
      mainPrice: 15,
      rating: 5,
      category: 'Baby Care',
    ),
    ProductModel(
      name: 'Baby Shampoo',
      weight: '200 ml',
      cover: 'https://i.imgur.com/mGRqfnc.png',
      images: ['https://i.imgur.com/mGRqfnc.png'],
      price: 6,
      mainPrice: 8,
      rating: 5,
      category: 'Baby Care',
    ),
    ProductModel(
      name: 'Baby Lotion',
      weight: '150 ml',
      cover: 'https://i.imgur.com/mGRqfnc.png',
      images: ['https://i.imgur.com/mGRqfnc.png'],
      price: 7,
      mainPrice: 9,
      rating: 4,
      category: 'Baby Care',
    ),
    ProductModel(
      name: 'Baby Powder',
      weight: '100 g',
      cover: 'https://i.imgur.com/mGRqfnc.png',
      images: ['https://i.imgur.com/mGRqfnc.png'],
      price: 5,
      mainPrice: 7,
      rating: 4,
      category: 'Baby Care',
    ),

    /// 💄 BEAUTY
    ProductModel(
      name: 'Face Wash',
      weight: '200 ml',
      cover: 'https://i.imgur.com/DNr8a6R.png',
      images: ['https://i.imgur.com/DNr8a6R.png'],
      price: 8,
      mainPrice: 10,
      rating: 5,
      category: 'Beauty',
    ),
    ProductModel(
      name: 'Lipstick',
      weight: '1 pc',
      cover: 'https://i.imgur.com/DNr8a6R.png',
      images: ['https://i.imgur.com/DNr8a6R.png'],
      price: 6,
      mainPrice: 9,
      rating: 4,
      category: 'Beauty',
    ),
    ProductModel(
      name: 'Perfume',
      weight: '50 ml',
      cover: 'https://i.imgur.com/DNr8a6R.png',
      images: ['https://i.imgur.com/DNr8a6R.png'],
      price: 10,
      mainPrice: 14,
      rating: 5,
      category: 'Beauty',
    ),

    /// 🏋️ GYM EQUIPMENT
    ProductModel(
      name: 'Dumbbell',
      weight: '5 kg',
      cover: 'https://i.imgur.com/O2ZX5nR.png',
      images: ['https://i.imgur.com/O2ZX5nR.png'],
      price: 20,
      mainPrice: 25,
      rating: 4,
      category: 'Gym Equipment',
    ),
    ProductModel(
      name: 'Yoga Mat',
      weight: '1 pc',
      cover: 'https://i.imgur.com/O2ZX5nR.png',
      images: ['https://i.imgur.com/O2ZX5nR.png'],
      price: 12,
      mainPrice: 15,
      rating: 5,
      category: 'Gym Equipment',
    ),
    ProductModel(
      name: 'Skipping Rope',
      weight: '1 pc',
      cover: 'https://i.imgur.com/O2ZX5nR.png',
      images: ['https://i.imgur.com/O2ZX5nR.png'],
      price: 5,
      mainPrice: 7,
      rating: 4,
      category: 'Gym Equipment',
    ),
  ];

  /// =========================
  /// 📦 BUNDLES (TETAP)
  /// =========================
  static List<BundleModel> bundles = [
    BundleModel(
      name: 'Bundle Pack',
      cover: 'https://i.imgur.com/Y0IFT2g.png',
      itemNames: ['Onion, Oil, Salt'],
      price: 35,
      mainPrice: 50.32,
      rating: 4,
    ),
  ];
}